//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyOfAC
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Collections.Generic;
    
    public partial class MemberShip
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "please tell about your expertise!")]
       
        public string Expertise { get; set; }
        [Required(ErrorMessage = "please Enter your answer!")]
       
        public string Question1 { get; set; }
        [Required(ErrorMessage = "please Enter your answer!")]
        
        public string Question2 { get; set; }
        public string RegistrationNumber { get; set; }
        [Required(ErrorMessage = "please select a team!")]
        public string Team { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<bool> emailsend { get; set; }
    
        public virtual Registration Registration { get; set; }
    }
}
