//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyOfAC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class upload_image
    {
        public int id { get; set; }
        [Display(Name = "Description")]
        public string img_description { get; set; }
        [Display(Name = "Image")]
        public string img_path { get; set; }
        [Display(Name = "Event Name")]
        public string MainHeading { get; set; }

        //
        [DataType(DataType.Date)]
        //[DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> Date { get; set; }
        [DataType(DataType.Time)]

        public Nullable<System.TimeSpan> Time { get; set; }

        public string Venue { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
