//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyOfAC
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class upload_image
    {
        public int id { get; set; }
        public string img_description { get; set; }
        public string img_path { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
    }
}
