//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocietyOfAC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SocietyofACEntities1 : DbContext
    {
        public SocietyofACEntities1()
            : base("name=SocietyofACEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MemberShip> MemberShips { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<upload_image> upload_image { get; set; }
    }
}
